/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.uebercomputing.mailrecord;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface BinaryMailRecordProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"BinaryMailRecordProtocol\",\"namespace\":\"com.uebercomputing.mailrecord\",\"version\":\"1.0.0\",\"types\":[{\"type\":\"record\",\"name\":\"BinaryMailRecord\",\"fields\":[{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"to\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"],\"default\":null},{\"name\":\"cc\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"],\"default\":null},{\"name\":\"bcc\",\"type\":[{\"type\":\"array\",\"items\":\"string\"},\"null\"],\"default\":null},{\"name\":\"dateUtcEpoch\",\"type\":\"long\"},{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"mailFields\",\"type\":[{\"type\":\"map\",\"values\":\"string\"},\"null\"],\"default\":null},{\"name\":\"body\",\"type\":\"bytes\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends BinaryMailRecordProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.uebercomputing.mailrecord.BinaryMailRecordProtocol.PROTOCOL;
  }
}